AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-5f468971
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-c19ecd89
Resources:
  Argus01ServicesModelOrganizationApi:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-14c5486b
      KeyName: boomer-key
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "boomer-${EnvironmentName}"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum install -y httpd
            /etc/init.d/httpd start
            chkconfig httpd on
            touch /var/www/html/index.html
            echo "<b><center><h1>I am from node1" > /var/www/html/index.html